version: '3.4'

services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "80:80"
    restart: "unless-stopped"